# Generated by Django 5.2.12 on 2026-04-25 18:32

import autoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=1, validators=[autoapp.models.validate_seats]),
        ),
        migrations.AddField(
            model_name='car',
            name='tnasmission',
            field=models.CharField(default='benzin', max_length=15, validators=[autoapp.models.validate_transmission]),
        ),
    ]
