# Generated by Django 5.2.12 on 2026-04-25 18:34

import autoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0002_car_seats_car_tnasmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tnasmission',
            field=models.CharField(default='mexanik', max_length=15, validators=[autoapp.models.validate_transmission]),
        ),
    ]
